### ISSUE TITLE
Non-free backgrounds

### ISSUE THREAD

**Issue by kkofler** [Rescator7/Hearts#2]
Unfortunately, your latest release (1.8) adds some backgrounds under the [Unsplash license](https://unsplash.com/license). The KDE project [thinks](https://phabricator.kde.org/D18078#401394) that this license contains restrictions that "do not comply with the KDE manifesto, with the Free Software Foundation definition of freedom, with the Debian Free Software Guidelines or with the Open Source Definition". Unfortunately, this precludes shipping those files in popular GNU/Linux distributions such as Fedora and Debian. (We would have to repackage the game with those images removed or replaced, unless we can get ahold of the contributors who uploaded the images to Unsplash and get them to grant an alternative license. Getting a relicensing from Unsplash themselves is theoretically possible but unlikely to happen.)

**Comment by Rescator7** [comment]
Interesting. I've chose those images because the Unsplash license is very permissive and seems fine for my application, but i understand that those images doesn't fit the Fedora or Debian Guidelines. I don't mind to replace them with public domain images, but it's not always obvious to find great images in a short period of time with the perfect license. Any suggestions here? Beside, Quote: "We would have to repackage the game". Is there an interest in packaging Hearts? As far as i know only OpenSuSe, and MX made a package using previous version of Hearts 1.4.

**Comment by kkofler** [comment]
Thank you for your quick reply. I am interested in having this game on Fedora, I may end up packaging it (I am a Fedora packager with experience with Qt and KDE packages), but so far I have only taken a cursory look and not yet started writing a package specfile.

**Comment by Rescator7** [comment]
Hello!

I've got a look around about our discussion, and found that some nice images could be
used from https://commons.wikimedia.org, they have public and CC 4 Images. 

But, i also read KDE manifesto and LIcenses_Policy at

https://community.kde.org/Policies/Licensing_Policy

They don't seems to allow CC 3 which is even more bothersome. 

Lot of sounds used by Hearts are CC 3. The russian deck is CC BY-SA 3.0., etc...
You can check all the Licenses icons, sounds, images used by Hearts in:

https://github.com/Rescator7/Hearts/blob/master/Credits

I think, it's gonna be very difficult to follow this policy.
Changing the 6 images would be easy, but all the sounds, icons that aren't CC 4.
Would be too hard.

**Comment by kkofler** [comment]
CC 3 licenses are OK for us distributors. KDE has a stricter policy on what licenses are allowed in their project to avoid license compatibility issues. This does not mean that the legacy versions of the licenses are non-free or not Open Source.

In addition, the CC-BY license allows relicensing under almost any license as long as the attribution is present, and the CC-BY-SA license explicitly allows distributing derivatives under a later version (see paragraph 3.b.1), so the exact version of a CC license is typically a non-issue. What really matters with CC licenses is that it is **not** an NC or ND license.

**Comment by kkofler** [comment]
That said, what may be a concern in a legal review is that you are embedding content under various share-alike licenses into one file through the QRC mechanism. You have an icon under the GPLv3, which is not directly compatible with CC-BY-SA 3.0 according to https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses . It is compatible with CC-BY-SA 4.0, but https://wiki.creativecommons.org/wiki/ShareAlike_compatibility is a mess. (Apparently, it takes a lawyer to know whether and when exactly CC-BY-SA 3.0 content can be relicensed under 4.0. Just transitively applying the compatibility rules is not allowed according to CC.) (I guess this is one of the reasons why KDE wants only 4.0 content) I think shipping separate files in a directory would be safer than embedding them all in the executable.

**Comment by kkofler** [comment]
And for the Russian card deck, where have you found that it is CC-BY-SA-3.0 licensed? If I check your link:
https://ru.wikipedia.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:%D0%98%D0%B3%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%BA%D0%B0%D1%80%D1%82%D1%8B
the individual cards appear to be all CC0 1.0, and it states that they are extracted from:
https://commons.wikimedia.org/wiki/File:Atlasnye_playing_cards_deck.svg
which is also CC0.

These licenses are no problem to embed into your QRC file and will not affect the licensing of the whole executable nor of other artwork:
* Public Domain
* CC0 (any version)
* CC-BY (any version)
* LGPL (any version)

It is the existing icon under the GPL (for which there are definitely possible replacements under non-copyleft licenses) and anything under CC-BY-SA that I would be concerned about.

**Comment by kkofler** [comment]
Note that Public Domain, CC0 and CC-BY (and your code license MIT) are compatible with basically any license, whereas the LGPL can also be a problem if mixed with a GPL-incompatible share-alike/copyleft license such as CC-BY-SA 3.0.

**Comment by kkofler** [comment]
By the way, there is also a Public Domain card deck (actually, several variants of the same design are available) designed by a Fedora artist (Nicu Buculei), which also ships in the KDE (the ornamental and white versions) and GNOME (the ornamental version) card deck sets: http://nicubunu.ro/cards/

**Comment by Rescator7** [comment]
1) I'll get rid of the GNU icon. I'll try to find 1 public domain, or i'll create 1 myself.

2) You are right about the Russian deck. I don't read Russian ! It's CC1. I'll fix the link in credits.
I got confused with the link below the cards at:

https://ru.wikipedia.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:%D0%98%D0%B3%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%BA%D0%B0%D1%80%D1%82%D1%8B

екст доступен по лицензии Creative Commons Attribution-ShareAlike; в отдельных случаях могут действовать дополнительные условия. Подробнее см. Условия использования.
Wikipedia® — зарегистрированный товарный знак некоммерческой организации Wikimedia Foundation, Inc.

NOTE: Russian cards deck was a requested by AndNovember, but it's been a while we didn't contact.

https://build.opensuse.org/package/show/home:AndnoVember:LXQT/hearts

3) I'll get a look at the Fedora card deck. But, it won't be my priority yet.

More to comes, more to check tomorrow.

**Comment by kkofler** [comment]
Hint: You can get the UI parts in English with:
https://ru.wikipedia.org/wiki/%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD:%D0%98%D0%B3%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%BA%D0%B0%D1%80%D1%82%D1%8B?uselang=en

At Wikipedia, the CC-BY-SA 3.0 license applies to the text, and to the work as a whole. Images can be under more permissive licenses.

As for the Nicu card deck ("Nicu" is the name used in KDE, more precisely "Nicu (ornamental)" and "Nicu (white)"), no need to rush, you don't **have** to add it, it's just a suggestion, so it is not a priority for me either.

**Comment by Rescator7** [comment]
I removed the GNU icon.

Yesterday, i was looking for some CC images for the background. Unfortunetly, that was before reading your post. Some are CC-BY-SA 3.0 and CC-BY-SA 4.0. Only 1 is CC-BY 3.0. I'l start over and stick to CC-BY-3 or Public. I want to keep the standard deck which is LGPL 2.1, so i'll avoid CC-BY-SA. It's not only the license. I have to try them see if it's looks good in the game, if the "streching" is decent in FULL screen (on 17" and 24" screen), etc... It takes time.

I'll probably give a try to the Nicu. It's pretty easy to add a new deck. If it's looks good i'll choose only 1, because they are too similar to use them all.

**Comment by Rescator7** [comment]
All images has been replaced by CC-BY only.
The nicu (white) has been added.

Let me know if you think something is wrong.
After that, i'll create new screenshot, and close this issue.

thanks.

**Comment by kkofler** [comment]
Nice, licensing should be fine now, now it's just up to me to start packaging. :-)

**Comment by kkofler** [comment]
For the screenshots, it would be helpful to replace the 1.8 screenshots in the `screenshots` directory with the revised ones, so that a GitHub archive tarball does not contain the files with the Unsplash backgrounds.

**Comment by kkofler** [comment]
Thanks! I think you can close this now.

One last (at least for now) request though: can you please create a tag for 1.8.3? It is nicer for packaging to have a tag than just a commit ID. (I have compiled and tried your game and it is definitely worth packaging, so I'll try to package it ASAP.)
