### ISSUE TITLE
Disgusting visual aspekt with pink hearts

### ISSUE THREAD

**Issue by atirage21** [Rescator7/Hearts#4]
Gnome hearts had more better visual aspekt. Please remove there stupid pink hearts from background of player names.

**Comment by atirage21** [comment]
Also you know add sothing normal backgrounds for card games from old gnome games. Here is good background:
![pxfuel](https://github.com/user-attachments/assets/92de2e56-c84c-4e3f-a432-696a122c6d75)

**Comment by atirage21** [comment]
Source: https://askubuntu.com/questions/29199/how-do-i-add-a-background-in-aisleriot-solitaire

**Comment by Rescator7** [comment]
The background you sent looks good, but it must have a compatible license to be included in this software. 
it must be under a license like CC-BY or public domain. This does not appear to be the case.

Maybe I could add an option to select an external image to set as the background... I have to think about that.

I like the pink heart... anyway, the game is completely open and free. It is always possible to modify your own version, and remove it.
I don't think it looks as good without it, and I don't have anything better to replace it with.

**Comment by atirage21** [comment]
OK, but these pink hearts look as from s.x shop or s.x bar. For background you know cut or direct use these tables from openclipart:
https://openclipart.org/detail/299936/wood-texture
https://openclipart.org/detail/282091/pool-table
https://openclipart.org/detail/289064/leaves-pattern
https://openclipart.org/detail/265443/autumn-grass
https://openclipart.org/detail/265995/patchy-grass

**Comment by atirage21** [comment]
replacing for pink hearts:

https://openclipart.org/detail/286998/leaves

or using more colours of hearts:
https://openclipart.org/detail/273031/valentine-conversation-hearts

or cpu vs human:
https://openclipart.org/detail/181150/shadow-of-person-standing-leg-cross-and-put-hands-in-the-pockets
https://openclipart.org/detail/89275/computer-icon

**Comment by atirage21** [comment]
Everything on openclipart use [Creative Commons Zero 1.0 Public Domain License](http://creativecommons.org/publicdomain/zero/1.0/)

**Comment by Rescator7** [comment]
> OK, but these pink hearts look as from s.x shop or s.x bar. For background you know cut or direct use these tables from openclipart: https://openclipart.org/detail/299936/wood-texture https://openclipart.org/detail/282091/pool-table https://openclipart.org/detail/289064/leaves-pattern https://openclipart.org/detail/265443/autumn-grass https://openclipart.org/detail/265995/patchy-grass

Oh my God. a s*x shop!? I've never been there, I can't say. Well, I guess it's my fault the original hearts were blue. I modified them to be pink. The game is called Hearts, so I thought using Hearts to display the score would be in theme. I'll check out openclipart and see if I like the stuff there.

**Comment by atirage21** [comment]
Grey hearts would be better as neutral color to all backgrounds.

**Comment by atirage21** [comment]
OK, i add my created idea for background of your hearts in my tee making time. Your loving of heart would be satisfied.

![Background for game Hearts](https://github.com/user-attachments/assets/1033a9a1-1449-4bfb-99cd-687eaa3f35e7)

**Comment by atirage21** [comment]
And here  is 
![Background for game Hearts2](https://github.com/user-attachments/assets/045d4732-9281-405c-8310-c302c4df233b)
second table background.

**Comment by Rescator7** [comment]
^Well, it would be better without Hearts in the middle, because there is object above there, It will not looks that great.

Anyway, i've already started to works on a new version 1.9... but, **this will takes a couple of days...**

I won't "remove" the hearts pink instead it will be possible to choose between:
- pink hearts
- gray hearts
- (possibly text only) 
- (possibly human/cpu)

I will add more backgrounds... here's some example. 1 of them you were suggesting.

I will add more options too. eg: it will be possible to disable/enable the card display, etc.

![screenshot1](https://github.com/user-attachments/assets/692e1a9c-4277-438d-9808-1ca5f3fe5316)
![screenshot2](https://github.com/user-attachments/assets/51285aa9-ff2d-48f2-a3b8-93ec6f593b9a)

**Comment by atirage21** [comment]
Try this also. It was preprared for your project in resolution 1920x1080:
![Green moon for Game Heart_1920x1080](https://github.com/user-attachments/assets/2ed06248-c87c-4a56-a718-0584d0cdc85d)

**Comment by atirage21** [comment]
Maybe only menu line it would be now better in grey color as are hearts or in system color..

**Comment by Rescator7** [comment]
I will add those backgrounds along with the previous 2. (I'm showing them with gray hearts only)
You will need to tells me what you want to see as credit, and what license for your background? (CC-BY or public)
Still a couples of days to complete the codes...

![screenshot3](https://github.com/user-attachments/assets/c29f584a-7c9f-4aa1-aa4a-c93401e1c747)
![screenshot4](https://github.com/user-attachments/assets/da9ee82c-75f0-464b-bc78-f07d3b6ad3a8)
![screenshot5](https://github.com/user-attachments/assets/c6f09485-88c3-476e-aed6-acaddb181770)
![screenshot6](https://github.com/user-attachments/assets/b7e786a6-17a0-462c-8f84-8c9aaeac03d3)

**Comment by Rescator7** [comment]
Preview CPU + Human 
![screenshot10](https://github.com/user-attachments/assets/300fc1c7-8c81-4cf2-a4d0-d1d4e38775e3)

**Comment by atirage21** [comment]
Yes, it is more useful for player. 

S pozdravom / Mit freundlichen Grüßen / Baráti udvozlettel / Best regards

Ing. Attila Tóth, PhD.

tel : +421 910 299 189 (4Ka - Slovak Republic)

Please consider your environmental responsibility before printing this 
e-mail 





________________________________
Od: Rescator7 ***@***.***>
Odoslané: nedeľa 27. októbra 2024 2:08
Komu: Rescator7/Hearts
Kópia: atirage21; State change
Predmet: Re: [Rescator7/Hearts] Disgusting visual aspekt with pink hearts (Issue #4)

Preview CPU + Human
screenshot10.png (view on web)

**Comment by Rescator7** [comment]
version 1.9
